/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRequestsRouteImport } from './routes/customer.requests'
import { Route as CustomerRateRouteImport } from './routes/customer.rate'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerOnboardingRouteImport } from './routes/customer.onboarding'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerNewRequestRouteImport } from './routes/customer.new-request'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as CustomerInvoicesRouteImport } from './routes/customer.invoices'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerChatRouteImport } from './routes/customer.chat'
import { Route as CustomerAmcRouteImport } from './routes/customer.amc'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppQuotationsRouteImport } from './routes/app.quotations'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppActiveRouteImport } from './routes/app.active'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as CustomerRequestsIdRouteImport } from './routes/customer.requests.$id'
import { Route as AppRequestsIdRouteImport } from './routes/app.requests.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRequestsRoute = CustomerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerRateRoute = CustomerRateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOnboardingRoute = CustomerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNewRequestRoute = CustomerNewRequestRouteImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerInvoicesRoute = CustomerInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerChatRoute = CustomerChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAmcRoute = CustomerAmcRouteImport.update({
  id: '/amc',
  path: '/amc',
  getParentRoute: () => CustomerRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppActiveRoute = AppActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerRequestsIdRoute = CustomerRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerRequestsRoute,
} as any)
const AppRequestsIdRoute = AppRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/active': typeof AppActiveRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/requests': typeof AppRequestsRouteWithChildren
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/customer/amc': typeof CustomerAmcRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/invoices': typeof CustomerInvoicesRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/new-request': typeof CustomerNewRequestRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/onboarding': typeof CustomerOnboardingRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/rate': typeof CustomerRateRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/active': typeof AppActiveRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/requests': typeof AppRequestsRouteWithChildren
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/customer/amc': typeof CustomerAmcRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/invoices': typeof CustomerInvoicesRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/new-request': typeof CustomerNewRequestRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/onboarding': typeof CustomerOnboardingRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/rate': typeof CustomerRateRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/active': typeof AppActiveRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/requests': typeof AppRequestsRouteWithChildren
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/customer/amc': typeof CustomerAmcRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/invoices': typeof CustomerInvoicesRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/new-request': typeof CustomerNewRequestRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/onboarding': typeof CustomerOnboardingRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/rate': typeof CustomerRateRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/customer'
    | '/login'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/marketing'
    | '/admin/profile'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/users'
    | '/app/active'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quotations'
    | '/app/requests'
    | '/app/schedule'
    | '/app/settings'
    | '/customer/amc'
    | '/customer/chat'
    | '/customer/dashboard'
    | '/customer/invoices'
    | '/customer/login'
    | '/customer/new-request'
    | '/customer/notifications'
    | '/customer/onboarding'
    | '/customer/profile'
    | '/customer/rate'
    | '/customer/requests'
    | '/app/requests/$id'
    | '/customer/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/customer'
    | '/login'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/marketing'
    | '/admin/profile'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/users'
    | '/app/active'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quotations'
    | '/app/requests'
    | '/app/schedule'
    | '/app/settings'
    | '/customer/amc'
    | '/customer/chat'
    | '/customer/dashboard'
    | '/customer/invoices'
    | '/customer/login'
    | '/customer/new-request'
    | '/customer/notifications'
    | '/customer/onboarding'
    | '/customer/profile'
    | '/customer/rate'
    | '/customer/requests'
    | '/app/requests/$id'
    | '/customer/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/customer'
    | '/login'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/marketing'
    | '/admin/profile'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/users'
    | '/app/active'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quotations'
    | '/app/requests'
    | '/app/schedule'
    | '/app/settings'
    | '/customer/amc'
    | '/customer/chat'
    | '/customer/dashboard'
    | '/customer/invoices'
    | '/customer/login'
    | '/customer/new-request'
    | '/customer/notifications'
    | '/customer/onboarding'
    | '/customer/profile'
    | '/customer/rate'
    | '/customer/requests'
    | '/app/requests/$id'
    | '/customer/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/requests': {
      id: '/customer/requests'
      path: '/requests'
      fullPath: '/customer/requests'
      preLoaderRoute: typeof CustomerRequestsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/rate': {
      id: '/customer/rate'
      path: '/rate'
      fullPath: '/customer/rate'
      preLoaderRoute: typeof CustomerRateRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/onboarding': {
      id: '/customer/onboarding'
      path: '/onboarding'
      fullPath: '/customer/onboarding'
      preLoaderRoute: typeof CustomerOnboardingRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/new-request': {
      id: '/customer/new-request'
      path: '/new-request'
      fullPath: '/customer/new-request'
      preLoaderRoute: typeof CustomerNewRequestRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/invoices': {
      id: '/customer/invoices'
      path: '/invoices'
      fullPath: '/customer/invoices'
      preLoaderRoute: typeof CustomerInvoicesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/chat': {
      id: '/customer/chat'
      path: '/chat'
      fullPath: '/customer/chat'
      preLoaderRoute: typeof CustomerChatRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/amc': {
      id: '/customer/amc'
      path: '/amc'
      fullPath: '/customer/amc'
      preLoaderRoute: typeof CustomerAmcRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/active': {
      id: '/app/active'
      path: '/active'
      fullPath: '/app/active'
      preLoaderRoute: typeof AppActiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/requests/$id': {
      id: '/customer/requests/$id'
      path: '/$id'
      fullPath: '/customer/requests/$id'
      preLoaderRoute: typeof CustomerRequestsIdRouteImport
      parentRoute: typeof CustomerRequestsRoute
    }
    '/app/requests/$id': {
      id: '/app/requests/$id'
      path: '/$id'
      fullPath: '/app/requests/$id'
      preLoaderRoute: typeof AppRequestsIdRouteImport
      parentRoute: typeof AppRequestsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRequestsRouteChildren {
  AppRequestsIdRoute: typeof AppRequestsIdRoute
}

const AppRequestsRouteChildren: AppRequestsRouteChildren = {
  AppRequestsIdRoute: AppRequestsIdRoute,
}

const AppRequestsRouteWithChildren = AppRequestsRoute._addFileChildren(
  AppRequestsRouteChildren,
)

interface AppRouteChildren {
  AppActiveRoute: typeof AppActiveRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppRequestsRoute: typeof AppRequestsRouteWithChildren
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActiveRoute: AppActiveRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppRequestsRoute: AppRequestsRouteWithChildren,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CustomerRequestsRouteChildren {
  CustomerRequestsIdRoute: typeof CustomerRequestsIdRoute
}

const CustomerRequestsRouteChildren: CustomerRequestsRouteChildren = {
  CustomerRequestsIdRoute: CustomerRequestsIdRoute,
}

const CustomerRequestsRouteWithChildren =
  CustomerRequestsRoute._addFileChildren(CustomerRequestsRouteChildren)

interface CustomerRouteChildren {
  CustomerAmcRoute: typeof CustomerAmcRoute
  CustomerChatRoute: typeof CustomerChatRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerInvoicesRoute: typeof CustomerInvoicesRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerNewRequestRoute: typeof CustomerNewRequestRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerOnboardingRoute: typeof CustomerOnboardingRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerRateRoute: typeof CustomerRateRoute
  CustomerRequestsRoute: typeof CustomerRequestsRouteWithChildren
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAmcRoute: CustomerAmcRoute,
  CustomerChatRoute: CustomerChatRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerInvoicesRoute: CustomerInvoicesRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerNewRequestRoute: CustomerNewRequestRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerOnboardingRoute: CustomerOnboardingRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerRateRoute: CustomerRateRoute,
  CustomerRequestsRoute: CustomerRequestsRouteWithChildren,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
