/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRequestsRouteImport } from './routes/customer.requests'
import { Route as CustomerRateRouteImport } from './routes/customer.rate'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerOnboardingRouteImport } from './routes/customer.onboarding'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerNewRequestRouteImport } from './routes/customer.new-request'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as CustomerInvoicesRouteImport } from './routes/customer.invoices'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerChatRouteImport } from './routes/customer.chat'
import { Route as CustomerAmcRouteImport } from './routes/customer.amc'
import { Route as AppVerificationRouteImport } from './routes/app.verification'
import { Route as AppSignupRouteImport } from './routes/app.signup'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppQuotationsRouteImport } from './routes/app.quotations'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppActiveRouteImport } from './routes/app.active'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminGrievancesRouteImport } from './routes/admin.grievances'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as CustomerRequestsIdRouteImport } from './routes/customer.requests.$id'
import { Route as CustomerProfileSectionRouteImport } from './routes/customer.profile.$section'
import { Route as CustomerGrievancesNewRouteImport } from './routes/customer.grievances.new'
import { Route as AppRequestsIdRouteImport } from './routes/app.requests.$id'
import { Route as AppJobsIdRouteImport } from './routes/app.jobs.$id'
import { Route as AppGrievancesNewRouteImport } from './routes/app.grievances.new'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'
import { Route as AdminProvidersIdRouteImport } from './routes/admin.providers.$id'
import { Route as AdminJobsIdRouteImport } from './routes/admin.jobs.$id'
import { Route as AdminGrievancesNewRouteImport } from './routes/admin.grievances.new'
import { Route as AdminGrievancesIdRouteImport } from './routes/admin.grievances.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRequestsRoute = CustomerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerRateRoute = CustomerRateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOnboardingRoute = CustomerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNewRequestRoute = CustomerNewRequestRouteImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerInvoicesRoute = CustomerInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerChatRoute = CustomerChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAmcRoute = CustomerAmcRouteImport.update({
  id: '/amc',
  path: '/amc',
  getParentRoute: () => CustomerRoute,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppActiveRoute = AppActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrievancesRoute = AdminGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerRequestsIdRoute = CustomerRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerRequestsRoute,
} as any)
const CustomerProfileSectionRoute = CustomerProfileSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => CustomerProfileRoute,
} as any)
const CustomerGrievancesNewRoute = CustomerGrievancesNewRouteImport.update({
  id: '/grievances/new',
  path: '/grievances/new',
  getParentRoute: () => CustomerRoute,
} as any)
const AppRequestsIdRoute = AppRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRequestsRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGrievancesNewRoute = AppGrievancesNewRouteImport.update({
  id: '/grievances/new',
  path: '/grievances/new',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRequestsRoute,
} as any)
const AdminProvidersIdRoute = AdminProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProvidersRoute,
} as any)
const AdminJobsIdRoute = AdminJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminJobsRoute,
} as any)
const AdminGrievancesNewRoute = AdminGrievancesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminGrievancesRoute,
} as any)
const AdminGrievancesIdRoute = AdminGrievancesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminGrievancesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/grievances': typeof AdminGrievancesRouteWithChildren
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/active': typeof AppActiveRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/requests': typeof AppRequestsRouteWithChildren
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signup': typeof AppSignupRoute
  '/app/verification': typeof AppVerificationRoute
  '/customer/amc': typeof CustomerAmcRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/invoices': typeof CustomerInvoicesRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/new-request': typeof CustomerNewRequestRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/onboarding': typeof CustomerOnboardingRoute
  '/customer/profile': typeof CustomerProfileRouteWithChildren
  '/customer/rate': typeof CustomerRateRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/admin/grievances/$id': typeof AdminGrievancesIdRoute
  '/admin/grievances/new': typeof AdminGrievancesNewRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/providers/$id': typeof AdminProvidersIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/app/grievances/new': typeof AppGrievancesNewRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/customer/grievances/new': typeof CustomerGrievancesNewRoute
  '/customer/profile/$section': typeof CustomerProfileSectionRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/grievances': typeof AdminGrievancesRouteWithChildren
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/active': typeof AppActiveRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/requests': typeof AppRequestsRouteWithChildren
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signup': typeof AppSignupRoute
  '/app/verification': typeof AppVerificationRoute
  '/customer/amc': typeof CustomerAmcRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/invoices': typeof CustomerInvoicesRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/new-request': typeof CustomerNewRequestRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/onboarding': typeof CustomerOnboardingRoute
  '/customer/profile': typeof CustomerProfileRouteWithChildren
  '/customer/rate': typeof CustomerRateRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/admin/grievances/$id': typeof AdminGrievancesIdRoute
  '/admin/grievances/new': typeof AdminGrievancesNewRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/providers/$id': typeof AdminProvidersIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/app/grievances/new': typeof AppGrievancesNewRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/customer/grievances/new': typeof CustomerGrievancesNewRoute
  '/customer/profile/$section': typeof CustomerProfileSectionRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/grievances': typeof AdminGrievancesRouteWithChildren
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/active': typeof AppActiveRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/requests': typeof AppRequestsRouteWithChildren
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signup': typeof AppSignupRoute
  '/app/verification': typeof AppVerificationRoute
  '/customer/amc': typeof CustomerAmcRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/invoices': typeof CustomerInvoicesRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/new-request': typeof CustomerNewRequestRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/onboarding': typeof CustomerOnboardingRoute
  '/customer/profile': typeof CustomerProfileRouteWithChildren
  '/customer/rate': typeof CustomerRateRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/admin/grievances/$id': typeof AdminGrievancesIdRoute
  '/admin/grievances/new': typeof AdminGrievancesNewRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/providers/$id': typeof AdminProvidersIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/app/grievances/new': typeof AppGrievancesNewRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/customer/grievances/new': typeof CustomerGrievancesNewRoute
  '/customer/profile/$section': typeof CustomerProfileSectionRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/customer'
    | '/login'
    | '/signup'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/grievances'
    | '/admin/jobs'
    | '/admin/marketing'
    | '/admin/profile'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/users'
    | '/app/active'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quotations'
    | '/app/requests'
    | '/app/schedule'
    | '/app/settings'
    | '/app/signup'
    | '/app/verification'
    | '/customer/amc'
    | '/customer/chat'
    | '/customer/dashboard'
    | '/customer/invoices'
    | '/customer/login'
    | '/customer/new-request'
    | '/customer/notifications'
    | '/customer/onboarding'
    | '/customer/profile'
    | '/customer/rate'
    | '/customer/requests'
    | '/admin/grievances/$id'
    | '/admin/grievances/new'
    | '/admin/jobs/$id'
    | '/admin/providers/$id'
    | '/admin/requests/$id'
    | '/admin/users/$id'
    | '/app/grievances/new'
    | '/app/jobs/$id'
    | '/app/requests/$id'
    | '/customer/grievances/new'
    | '/customer/profile/$section'
    | '/customer/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/customer'
    | '/login'
    | '/signup'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/grievances'
    | '/admin/jobs'
    | '/admin/marketing'
    | '/admin/profile'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/users'
    | '/app/active'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quotations'
    | '/app/requests'
    | '/app/schedule'
    | '/app/settings'
    | '/app/signup'
    | '/app/verification'
    | '/customer/amc'
    | '/customer/chat'
    | '/customer/dashboard'
    | '/customer/invoices'
    | '/customer/login'
    | '/customer/new-request'
    | '/customer/notifications'
    | '/customer/onboarding'
    | '/customer/profile'
    | '/customer/rate'
    | '/customer/requests'
    | '/admin/grievances/$id'
    | '/admin/grievances/new'
    | '/admin/jobs/$id'
    | '/admin/providers/$id'
    | '/admin/requests/$id'
    | '/admin/users/$id'
    | '/app/grievances/new'
    | '/app/jobs/$id'
    | '/app/requests/$id'
    | '/customer/grievances/new'
    | '/customer/profile/$section'
    | '/customer/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/customer'
    | '/login'
    | '/signup'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/grievances'
    | '/admin/jobs'
    | '/admin/marketing'
    | '/admin/profile'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/users'
    | '/app/active'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quotations'
    | '/app/requests'
    | '/app/schedule'
    | '/app/settings'
    | '/app/signup'
    | '/app/verification'
    | '/customer/amc'
    | '/customer/chat'
    | '/customer/dashboard'
    | '/customer/invoices'
    | '/customer/login'
    | '/customer/new-request'
    | '/customer/notifications'
    | '/customer/onboarding'
    | '/customer/profile'
    | '/customer/rate'
    | '/customer/requests'
    | '/admin/grievances/$id'
    | '/admin/grievances/new'
    | '/admin/jobs/$id'
    | '/admin/providers/$id'
    | '/admin/requests/$id'
    | '/admin/users/$id'
    | '/app/grievances/new'
    | '/app/jobs/$id'
    | '/app/requests/$id'
    | '/customer/grievances/new'
    | '/customer/profile/$section'
    | '/customer/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/requests': {
      id: '/customer/requests'
      path: '/requests'
      fullPath: '/customer/requests'
      preLoaderRoute: typeof CustomerRequestsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/rate': {
      id: '/customer/rate'
      path: '/rate'
      fullPath: '/customer/rate'
      preLoaderRoute: typeof CustomerRateRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/onboarding': {
      id: '/customer/onboarding'
      path: '/onboarding'
      fullPath: '/customer/onboarding'
      preLoaderRoute: typeof CustomerOnboardingRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/new-request': {
      id: '/customer/new-request'
      path: '/new-request'
      fullPath: '/customer/new-request'
      preLoaderRoute: typeof CustomerNewRequestRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/invoices': {
      id: '/customer/invoices'
      path: '/invoices'
      fullPath: '/customer/invoices'
      preLoaderRoute: typeof CustomerInvoicesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/chat': {
      id: '/customer/chat'
      path: '/chat'
      fullPath: '/customer/chat'
      preLoaderRoute: typeof CustomerChatRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/amc': {
      id: '/customer/amc'
      path: '/amc'
      fullPath: '/customer/amc'
      preLoaderRoute: typeof CustomerAmcRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/app/verification': {
      id: '/app/verification'
      path: '/verification'
      fullPath: '/app/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/signup': {
      id: '/app/signup'
      path: '/signup'
      fullPath: '/app/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/active': {
      id: '/app/active'
      path: '/active'
      fullPath: '/app/active'
      preLoaderRoute: typeof AppActiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grievances': {
      id: '/admin/grievances'
      path: '/grievances'
      fullPath: '/admin/grievances'
      preLoaderRoute: typeof AdminGrievancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/requests/$id': {
      id: '/customer/requests/$id'
      path: '/$id'
      fullPath: '/customer/requests/$id'
      preLoaderRoute: typeof CustomerRequestsIdRouteImport
      parentRoute: typeof CustomerRequestsRoute
    }
    '/customer/profile/$section': {
      id: '/customer/profile/$section'
      path: '/$section'
      fullPath: '/customer/profile/$section'
      preLoaderRoute: typeof CustomerProfileSectionRouteImport
      parentRoute: typeof CustomerProfileRoute
    }
    '/customer/grievances/new': {
      id: '/customer/grievances/new'
      path: '/grievances/new'
      fullPath: '/customer/grievances/new'
      preLoaderRoute: typeof CustomerGrievancesNewRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/app/requests/$id': {
      id: '/app/requests/$id'
      path: '/$id'
      fullPath: '/app/requests/$id'
      preLoaderRoute: typeof AppRequestsIdRouteImport
      parentRoute: typeof AppRequestsRoute
    }
    '/app/jobs/$id': {
      id: '/app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/app/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grievances/new': {
      id: '/app/grievances/new'
      path: '/grievances/new'
      fullPath: '/app/grievances/new'
      preLoaderRoute: typeof AppGrievancesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof AdminRequestsRoute
    }
    '/admin/providers/$id': {
      id: '/admin/providers/$id'
      path: '/$id'
      fullPath: '/admin/providers/$id'
      preLoaderRoute: typeof AdminProvidersIdRouteImport
      parentRoute: typeof AdminProvidersRoute
    }
    '/admin/jobs/$id': {
      id: '/admin/jobs/$id'
      path: '/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AdminJobsIdRouteImport
      parentRoute: typeof AdminJobsRoute
    }
    '/admin/grievances/new': {
      id: '/admin/grievances/new'
      path: '/new'
      fullPath: '/admin/grievances/new'
      preLoaderRoute: typeof AdminGrievancesNewRouteImport
      parentRoute: typeof AdminGrievancesRoute
    }
    '/admin/grievances/$id': {
      id: '/admin/grievances/$id'
      path: '/$id'
      fullPath: '/admin/grievances/$id'
      preLoaderRoute: typeof AdminGrievancesIdRouteImport
      parentRoute: typeof AdminGrievancesRoute
    }
  }
}

interface AdminGrievancesRouteChildren {
  AdminGrievancesIdRoute: typeof AdminGrievancesIdRoute
  AdminGrievancesNewRoute: typeof AdminGrievancesNewRoute
}

const AdminGrievancesRouteChildren: AdminGrievancesRouteChildren = {
  AdminGrievancesIdRoute: AdminGrievancesIdRoute,
  AdminGrievancesNewRoute: AdminGrievancesNewRoute,
}

const AdminGrievancesRouteWithChildren = AdminGrievancesRoute._addFileChildren(
  AdminGrievancesRouteChildren,
)

interface AdminJobsRouteChildren {
  AdminJobsIdRoute: typeof AdminJobsIdRoute
}

const AdminJobsRouteChildren: AdminJobsRouteChildren = {
  AdminJobsIdRoute: AdminJobsIdRoute,
}

const AdminJobsRouteWithChildren = AdminJobsRoute._addFileChildren(
  AdminJobsRouteChildren,
)

interface AdminProvidersRouteChildren {
  AdminProvidersIdRoute: typeof AdminProvidersIdRoute
}

const AdminProvidersRouteChildren: AdminProvidersRouteChildren = {
  AdminProvidersIdRoute: AdminProvidersIdRoute,
}

const AdminProvidersRouteWithChildren = AdminProvidersRoute._addFileChildren(
  AdminProvidersRouteChildren,
)

interface AdminRequestsRouteChildren {
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
}

const AdminRequestsRouteChildren: AdminRequestsRouteChildren = {
  AdminRequestsIdRoute: AdminRequestsIdRoute,
}

const AdminRequestsRouteWithChildren = AdminRequestsRoute._addFileChildren(
  AdminRequestsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminGrievancesRoute: typeof AdminGrievancesRouteWithChildren
  AdminJobsRoute: typeof AdminJobsRouteWithChildren
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminProvidersRoute: typeof AdminProvidersRouteWithChildren
  AdminRequestsRoute: typeof AdminRequestsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminGrievancesRoute: AdminGrievancesRouteWithChildren,
  AdminJobsRoute: AdminJobsRouteWithChildren,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminProvidersRoute: AdminProvidersRouteWithChildren,
  AdminRequestsRoute: AdminRequestsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRequestsRouteChildren {
  AppRequestsIdRoute: typeof AppRequestsIdRoute
}

const AppRequestsRouteChildren: AppRequestsRouteChildren = {
  AppRequestsIdRoute: AppRequestsIdRoute,
}

const AppRequestsRouteWithChildren = AppRequestsRoute._addFileChildren(
  AppRequestsRouteChildren,
)

interface AppRouteChildren {
  AppActiveRoute: typeof AppActiveRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppRequestsRoute: typeof AppRequestsRouteWithChildren
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignupRoute: typeof AppSignupRoute
  AppVerificationRoute: typeof AppVerificationRoute
  AppGrievancesNewRoute: typeof AppGrievancesNewRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActiveRoute: AppActiveRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppRequestsRoute: AppRequestsRouteWithChildren,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignupRoute: AppSignupRoute,
  AppVerificationRoute: AppVerificationRoute,
  AppGrievancesNewRoute: AppGrievancesNewRoute,
  AppJobsIdRoute: AppJobsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CustomerProfileRouteChildren {
  CustomerProfileSectionRoute: typeof CustomerProfileSectionRoute
}

const CustomerProfileRouteChildren: CustomerProfileRouteChildren = {
  CustomerProfileSectionRoute: CustomerProfileSectionRoute,
}

const CustomerProfileRouteWithChildren = CustomerProfileRoute._addFileChildren(
  CustomerProfileRouteChildren,
)

interface CustomerRequestsRouteChildren {
  CustomerRequestsIdRoute: typeof CustomerRequestsIdRoute
}

const CustomerRequestsRouteChildren: CustomerRequestsRouteChildren = {
  CustomerRequestsIdRoute: CustomerRequestsIdRoute,
}

const CustomerRequestsRouteWithChildren =
  CustomerRequestsRoute._addFileChildren(CustomerRequestsRouteChildren)

interface CustomerRouteChildren {
  CustomerAmcRoute: typeof CustomerAmcRoute
  CustomerChatRoute: typeof CustomerChatRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerInvoicesRoute: typeof CustomerInvoicesRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerNewRequestRoute: typeof CustomerNewRequestRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerOnboardingRoute: typeof CustomerOnboardingRoute
  CustomerProfileRoute: typeof CustomerProfileRouteWithChildren
  CustomerRateRoute: typeof CustomerRateRoute
  CustomerRequestsRoute: typeof CustomerRequestsRouteWithChildren
  CustomerGrievancesNewRoute: typeof CustomerGrievancesNewRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAmcRoute: CustomerAmcRoute,
  CustomerChatRoute: CustomerChatRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerInvoicesRoute: CustomerInvoicesRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerNewRequestRoute: CustomerNewRequestRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerOnboardingRoute: CustomerOnboardingRoute,
  CustomerProfileRoute: CustomerProfileRouteWithChildren,
  CustomerRateRoute: CustomerRateRoute,
  CustomerRequestsRoute: CustomerRequestsRouteWithChildren,
  CustomerGrievancesNewRoute: CustomerGrievancesNewRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
